### ISSUE TITLE
单机多卡跑train_m3e.py报错，

### ISSUE THREAD

**Issue by heavenhellchen** [wangyuxinwhy/uniem#68]
### 🐛 bug 说明

命令：accelerate launch python scripts/train_m3e.py /path/to/model_base/ /path/to/dataset/

报错
mnt/cache/zhaofufangchen/anaconda3/envs/m3e/lib/python3.10/site-packages/ac │
│ celerate/data_loader.py:742 in prepare_data_loader                           │
│                                                                              │
│   739 │   │   │   if sampler_is_batch_sampler:                               │
│   740 │   │   │   │   sampler = dataloader.sampler.sampler                   │
│   741 │   │   │   else:                                                      │
│ ❱ 742 │   │   │   │   sampler = dataloader.batch_sampler.sampler             │
│   743 │   │   │   if hasattr(sampler, "generator"):                          │
│   744 │   │   │   │   if sampler.generator is None:                          │
│   745 │   │   │   │   │   sampler.generator = torch.Generator()              │
│                                                                              │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮ │
│ │               dataloader = <torch.utils.data.dataloader.DataLoader       │ │
│ │                            object at 0x7f766b4b5180>                     │ │
│ │                   device = device(type='cuda', index=1)                  │ │
│ │         dispatch_batches = False                                         │ │
│ │             even_batches = True                                          │ │
│ │        new_batch_sampler = None                                          │ │
│ │              new_dataset = <uniem.data.M3EDataset object at              │ │
│ │                            0x7f78b4033cd0>                               │ │
│ │            num_processes = 8                                             │ │
│ │            process_index = 1                                             │ │
│ │            put_on_device = True                                          │ │
│ │                rng_types = ['generator']                                 │ │
│ │ sampler_is_batch_sampler = False                                         │ │
│ │            split_batches = False                                         │ │
│ │                    state = Distributed environment: MULTI_GPU  Backend:  │ │
│ │                            nccl                                          │ │
│ │                            Num processes: 8                              │ │
│ │                            Process index: 1                              │ │
│ │                            Local process index: 1                        │ │
│ │                            Device: cuda:1                                │ │
│ │                                                                          │ │
│ │                            Mixed precision type: no                      │ │
│ │   synchronized_generator = None                                          │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'sampler'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 132975) of binary: /mnt/cache/zhaofufangchen/anaconda3/envs/m3e/bin/python
Traceback (most recent call last):
  File "/mnt/cache/zhaofufangchen/anaconda3/envs/m3e/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/mnt/cache/zhaofufangchen/anaconda3/envs/m3e/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/mnt/cache/zhaofufangchen/anaconda3/envs/m3e/lib/python3.10/site-packages/accelerate/commands/launch.py", line 970, in launch_command
    multi_gpu_launcher(args)
  File "/mnt/cache/zhaofufangchen/anaconda3/envs/m3e/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/mnt/cache/zhaofufangchen/anaconda3/envs/m3e/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/mnt/cache/zhaofufangchen/anaconda3/envs/m3e/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/cache/zhaofufangchen/anaconda3/envs/m3e/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
scripts/train_m3e.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-07-25_13:27:50
  host      : SH-IDC1-10-198-6-78
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 132976)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-07-25_13:27:50
  host      : SH-IDC1-10-198-6-78
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 132977)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-07-25_13:27:50
  host      : SH-IDC1-10-198-6-78
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 132978)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2023-07-25_13:27:50
  host      : SH-IDC1-10-198-6-78
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 132979)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2023-07-25_13:27:50
  host      : SH-IDC1-10-198-6-78
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 132980)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2023-07-25_13:27:50
  host      : SH-IDC1-10-198-6-78
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 132981)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2023-07-25_13:27:50
  host      : SH-IDC1-10-198-6-78
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 132982)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-25_13:27:50
  host      : SH-IDC1-10-198-6-78
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 132975)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

请问这种问题怎么解决呢？如果需要什么更加详细的信息可以和我留言，这个问题确实困扰我很久了。。

### Python Version

3.10

**Comment by wangyuxinwhy** [comment]
我更新了 m3e 得脚本，添加了如下代码以支持分布式训练

```python
accelerator = Accelerator(
    mixed_precision=mixed_precision.value,
    gradient_accumulation_steps=gradient_accumulation_steps,
    project_config=project_config,
    log_with=['tensorboard'] if use_tensorboard else None,
    dispatch_batches=True,  # 注意这一行
    split_batches=True,  # 注意这一行
)

# hack dataloader for distributed training
train_dataloader.__dict__['batch_size'] = batch_size
train_dataloader = accelerator.prepare(train_dataloader)
train_dataloader.__dict__['sampler'] = SequentialSampler(train_dataloader.dataset)
train_dataloader.__dict__['batch_sampler'] = None
```

 M3E 的 dataset 为了保证多数据集下依然保持每个 batch 均属于同一任务，因此需要设置 batch_size=None ,让 DataLoader 通过 SequentialSampler 进行采样。而这种方式会导致 Accelerate 库无法正确的在分布式的环境下 prepare dataloader，所以会报你上面的这个错误。

添加了上方代码后，可以正确处理了，但整个方法非常的 hack ....

更好的处理方式是写一个针对 M3E 特殊的 BatchSampler ，但我当时偷懒就没这么做....

综上，您只需要更新到最新的代码就可以进行单机多卡的训练了，需要注意的是 M3E 的训练内存瓶颈主要在于 activation 即 ”激活内存“，所以使用 fsdp,ddp 等数据并行的方式，无法很好的拓展 batch_size 大小，需要通过 pipeline 并行或者 Tensor 并行来解决。
